
docker volume create postgres_dataversion: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - my-network

  spring-boot-app:
    image: your-spring-boot-image
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
